from setuptools import setup, find_packages

setup(
    name="sbom-test-setup",
    version="1.0.0",
    description="Python component for SBOM testing using setup.py",
    author="SBOM Test",
    license="MIT",
    python_requires=">=3.9",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "boto3==1.26.137",
        "botocore==1.29.137",
        "google-cloud-storage==2.9.0",
        "google-cloud-bigquery==3.11.0",
        "google-cloud-pubsub==2.17.0",
        "google-cloud-firestore==2.11.1",
        "google-api-python-client==2.88.0",
        "google-auth==2.19.1",
        "azure-storage-blob==12.16.0",
        "azure-identity==1.13.0",
        "azure-cosmos==4.4.0",
        "azure-keyvault-secrets==4.7.0",
        "docker==6.1.2",
        "kubernetes==26.1.0",
        "ansible==8.0.0",
        "fabric==3.1.0",
        "paramiko==3.2.0",
        "celery==5.3.0",
        "kombu==5.3.0",
        "dramatiq==1.14.2",
        "rq==1.15.1",
    ],
)
